function delete-fe-build-modules () {
  echo " <----> [ START ] <----> DELETING npm dependencies"
  echo " "
  rm -rfv $ROOT_DIR/$SRC_DIR/node_modules
  echo " "
  echo " <----> [ DONE ] <----> DELETING npm dependencies"
}

function clean-project () {
  echo " <----> [ START ] <----> 💥  Removing related folders/files of $PROJECT_NAME theme required files "
  echo " "
	echo " Cleaning ./build/mysql directory of temporary files "
  echo " Cleaning ./build/wordpress directory of temporary files "
  echo " "
	rm -rfv $ROOT_DIR/build/mysql/* $ROOT_DIR/build/wordpress/*
  echo " "
  echo " <----> [ DONE ] <----> 💥  Removing related folders/files of $PROJECT_NAME theme required files"
}

function pre-clean () {
  echo "1. backup old database"
  echo "2. save actual database"
  echo "3. backup uploads"
  echo "4. backup vendor-plugins"
}

function clean () {
  echo "remove all files generated by the previous build"
}

function post-clean () {
  echo "execute processes needed to finalize the project cleaning"
}