

function uni-web-install () {
  uni-web-install-docker-project
  install-fe-build
  copy_src_files
}

function uni-web-build () {
  echo "preapare package before deploy"
}

function uni-web-deploy () {
  echo "done in an integration or release environment"
  echo "copies the final package to the remote repository for sharing with other developers and projects"
}




function uni-web-pre-clean () {
  backup-db
  backup-updated-plugins
}

function uni-web-clean () {
  uni-web-stop-docker
  echo "remove all files generated by the previous build"
}

function uni-web-post-clean () {
  echo "execute processes needed to finalize the project cleaning"
}





function uni-web-pre-site () {
  echo "execute processes needed prior to the actual project site generation - clean dist and build/*/*/wordpress"
}

function uni-web-site () {
  echo "generate the project's site - fe-build compilation to dist"
}

function uni-web-post-site () {
  echo "execute processes needed to finalize the site generation, and to prepare for site deployment"
}

function uni-web-site-deploy () {
  echo "deploy the generated site files to the build/*/*/wordpress"
}

function uni-web-uninstall () {
  uni-web-pre-clean
  uni-web-clean
  delete-fe-build-modules 
  detele-build-files
}
