name: CI Release to Test
on:
  push:
    branches: [develop, release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use NodeJS v14.18.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Install
        run: npm run install:dependencies:ci

      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Test
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: test
          folder: .
